server:
  port: 11060
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:11060/eureka/