server:
  port: 11062
spring:
  application:
    name: servicec2
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lr_test2?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  rabbitmq:
    host: 172.16.2.30
    port: 5672
    username: admin
    password: 123457
    listener:
      type: simple
      simple:
        default-requeue-rejected: false
        acknowledge-mode: manual
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11060/eureka/