server:
  port: 11061
spring:
  application:
    name: servicec1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lr_test2?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11060/eureka/